#!/usr/bin/env node

/**
 * Generate data.js from problems.json, then bake into index.html
 */

const fs = require('fs');
const path = require('path');

const data = JSON.parse(fs.readFileSync(path.join(__dirname, 'problems.json'), 'utf-8'));

// Compact serialization: just the problems array, minified
const compact = JSON.stringify(data.problems);
const jsContent = `// Auto-generated by generate.js — do not edit directly
// Run: node generate.js
const LC_PROBLEMS = ${compact};
const LC_META = ${JSON.stringify(data.meta)};
`;

fs.writeFileSync(path.join(__dirname, 'data.js'), jsContent, 'utf-8');
console.log('Generated data.js');
